a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

print(f'Addition: {a} + {b} = {a + b}')
print(f'Subtraction: {a} - {b} = {a - b}')
print(f'Division: {a} / {b} = {a / b}')
print(f'Multiplication: {a} * {b} = {a * b}')
print(f'Exponent: {a} ** {b} = {a ** b}')
print(f'Modulus: {a} % {b} = {a % b}')
print(f'Floor division: {a} // {b} = {a // b}')